# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# if we haven't sourced the general config, do it
if not set -q __fish_general_config_sourced

  set --prepend fish_function_path /nix/store/1wvljvclw8yxahy7mpxhihb9pnvcjp58-fishplugin-foreign-env-git-20200209/share/fish/vendor_functions.d
  fenv source /Users/peter/.nix-profile/etc/profile.d/hm-session-vars.sh > /dev/null
  set -e fish_function_path[1]

  source /nix/store/hp5ryaw2rwq73031g7smhgyxj5214ghh-fzf-0.27.0/share/fzf/key-bindings.fish && fzf_key_bindings

/nix/store/f9hc9kdm8wd3xrakfjps1ljrpji26c5k-direnv-2.28.0/bin/direnv hook fish | source

  # and leave a note so we don't source this config section again from
  # this very shell (children will source the general config anew)
  set -g __fish_general_config_sourced 1

end

# if we haven't sourced the login config, do it
status --is-login; and not set -q __fish_login_config_sourced
and begin

  # Login shell initialisation
  set -xg TERM xterm-256color
if test -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  fenv source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
end
if test -e /nix/var/nix/profiles/default/etc/profile.d/nix.sh
  fenv source /nix/var/nix/profiles/default/etc/profile.d/nix.sh
end
if test -e $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh
  fenv source $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh
end
set -xg PATH $HOME/bin $HOME/.cabal/bin /Users/peter/.ghcup/bin $PATH
set -xg NIX_PATH $HOME/.nix-defexpr/channels $NIX_PATH
set -xg FZF_DEFAULT_OPTS "--preview='bat {} --color=always'" \n
set -xg TOOLCHAINS swift

fish_add_path ~/.cargo/bin/


  # and leave a note so we don't source this config section again from
  # this very shell (children will source the general config anew)
  set -g __fish_login_config_sourced 1

end

# if we haven't sourced the interactive config, do it
status --is-interactive; and not set -q __fish_interactive_config_sourced
and begin

  # Abbreviations
  

  # Aliases
  alias .. 'cd ..'
alias cat 'bat'
alias du 'ncdu --color dark -rr -x'
alias g 'git'
alias gc 'git commit -m'
alias gca 'git commit -am'
alias gforksync 'git fetch upstream && git merge upstream/master && git push origin master'
alias ghauth 'gh auth login --with-token < ~/.ghauth'
alias gl 'git log'
alias grep 'grep --color=auto'
alias gws 'git status'
alias l 'exa --long --header --git --all'
alias nixdaemon 'sudo launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist && launchctl start org.nixos.nix-daemon'
alias nixedit 'home-manager edit'
alias nixgc 'nix-collect-garbage -d'
alias nixq 'nix-env -qa'
alias nixre 'home-manager switch'
alias nixup 'nix-env -u'
alias nixupdate 'nix-channel --update'
alias nixupgrade 'nix upgrade-nix'
alias nixversion 'nix eval nixpkgs.lib.version'
alias ping 'prettyping'
alias ps 'procs'
alias tabninecfg 'vc /Users/peter/Library/Preferences/TabNine/TabNine.toml'
alias v 'nvim'

  # Prompt initialisation
  if test "$TERM" != "dumb"  -a \( -z "$INSIDE_EMACS"  -o "$INSIDE_EMACS" = "vterm" \)
  eval (/nix/store/j76kgcjnljf29majaywvhq6gzpvhmlff-starship-0.52.1/bin/starship init fish)
end

eval (direnv hook fish)
any-nix-shell fish --info-right | source


  # Interactive shell intialisation
  # add completions generated by Home Manager to $fish_complete_path
begin
  set -l joined (string join " " $fish_complete_path)
  set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
  set -l post_joined (string replace $prev_joined "" $joined)
  set -l prev (string split " " (string trim $prev_joined))
  set -l post (string split " " (string trim $post_joined))
  set fish_complete_path $prev "/Users/peter/.local/share/fish/home-manager_generated_completions" $post
end


  # and leave a note so we don't source this config section again from
  # this very shell (children will source the general config anew,
  # allowing configuration changes in, e.g, aliases, to propagate)
  set -g __fish_interactive_config_sourced 1

end
